#!/bin/sh
#
# Delegates to post-receive-email and post-receive-trac
#

input=""
while read line ; do
    input="$input$line"
done

echo $input | sh $GIT_DIR/hooks/post-receive-email
echo $input | sh $GIT_DIR/hooks/post-receive-trac

