#!/bin/sh
#
# Delegates to post-receive-email and post-receive-trac
#

input=""
while read line ; do
    input="$input$line"
done

echo $input | sh /srv/git/hooks/server/post-receive-email
echo $input | sh /srv/git/hooks/server/post-receive-trac

