#!/bin/sh

nl=$'\n'
input=""
while read newref oldref refname ; do
    input="$input$newref $oldref $refname$nl"
done

echo -n "$input" | sh /srv/git/hooks/server/pre-receive-only-one &&
echo -n "$input" | sh /srv/git/hooks/server/pre-receive-stable

