#!/bin/sh

refname="$1"
oldrev="$2"
newrev="$3"

ruby /srv/git/hooks/server/update-lock-check.rb "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-ensure-ticket-reference "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-allow-tags-branches "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-prefer-rebase "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-prefer-underscores "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-stable "$refname" "$oldrev" "$newrev" &&
sh /srv/git/hooks/server/update-ensure-follows "$refname" "$oldrev" "$newrev"

