#!/bin/sh

refname="$1"
oldrev="$2"
newrev="$3"

/srv/git/hooks/server/update-allow-tags-branches "$refname" "$oldrev" "$newrev" &&
/srv/git/hooks/server/update-prefer-rebase "$refname" "$oldrev" "$newrev"

