#!/bin/sh

. $(dirname $0)/functions

while read oldrev newrev refname ; do
	case "$refname" in
		refs/tags/*)
			short_refname=${refname##refs/tags/}
			;;
		refs/heads/*)
			short_refname=${refname##refs/heads/}
			;;
		*)
			echo >&2 "*** Unknown type of update to $refname"
			exit 1
			;;
	esac

	set_new_commits
	set_rev_types

	echo "$new_commits" | git rev-list --reverse --stdin | while read commit ; do
		set_describe "$commit"
		set_describe_tags "$commit"
		"$PYTHON" "$POST_RECEIVE_TRAC" "$TRAC_ENV" "$short_refname" "$describe" "$describe_tags" "$commit"
	done
done

exit 0

