#!/bin/sh

. $(dirname $0)/functions

touch "$GIT_DIR/commitnumbers"

while read oldrev newrev refname ; do
	set_new_commits
	echo "$new_commits" | git rev-list --reverse --stdin | while read commit ; do
		if [[ $(grep "$commit" "$GIT_DIR/commitnumbers") == "" ]] ; then
			echo "$commit" >> "$GIT_DIR/commitnumbers"
			number=$(grep --max-count=1 --line-number "$commit" "$GIT_DIR/commitnumbers" | grep -oP "^\d+(?=:)")
			git tag "r/$number" "$commit"
		fi
	done
done

