#!/bin/sh

. $(dirname $0)/functions

while read oldrev newrev refname ; do
	set_new_commits
	echo "$new_commits" | git rev-list --reverse --stdin | while read commit ; do
		"$PYTHON" "$POST_RECEIVE_TRAC" "$TRAC_ENV" "$commit"
	done
done

exit 0

