#!/bin/sh

. $(dirname $0)/functions

while read oldrev newrev refname ; do
	set_new_commits
	echo "$new_commits" | git rev-list --reverse --stdin | while read commit ; do
		cat $GIT_DIR/packed-refs | grep --quiet "$commit"
		if [ $? -ne 0 ] ; then
			current=$(cat $GIT_DIR/packed-refs | grep "refs/tags/r/" | tail -n 1 | grep -oP "r\/\d+" | grep -oP "\d+")
			if [ $? -ne 0 ] ; then
				next="0"
			else
				next=$(($current + 1))
			fi
			echo "$commit refs/tags/r/$next" >> $GIT_DIR/packed-refs
		fi
	done
done

