#!/bin/sh

i=0
while read oldrev newrev refname ; do
	i=$(($i + 1))
done

if [ $i -ne 1 ] ; then
	echo "----------------------------------------------------"
	echo
	echo "Only push one branch at a time"
	echo
	echo "----------------------------------------------------"
	exit 1
fi

