#!/bin/sh
#
# Simply enforces rate_tables instead of rateTables. Note
# that ratetables could still sneak when, but we'll give
# people the benefit of the doubt.

. $(dirname $0)/functions

# Command line
refname="$1"
oldrev="$2"
newrev="$3"

if expr "$oldrev" : '0*$' >/dev/null ; then
	if expr "$refname" : '.*[A-Z].*' ; then
		display_error_message "Please use underscored branch names (e.g. rate_tables)"
		exit 1
	fi
fi

