#!/bin/bash
#
# Creates a separate DAG in the repo to merge stable into.
#
# See the other docs about why this is a good idea.
#

# Make a root directory tree with no files in it
config_tree_hash=$(git mktree <<FOO
FOO
)

# Commit the root directory tree
commit_hash=$(git commit-tree $config_tree_hash <<FOO
Initial commit on stable branch.
FOO
)

echo "Made stable 0.0 commit $commit_hash"

# Save the commit to the stable ref for later pushing to origin
git update-ref refs/heads/stable "$commit_hash" 0000000000000000000000000000000000000000

