#!/bin/sh

. $(dirname $0)/functions

set_branch_name
if [ "$branch_name" == "" ] ; then
	echo "Not on a branch"
	exit 1
fi

git push origin $branch_name
if [[ $? -ne 0 ]] ; then
    exit $?
fi

# ...tags...

