#!/bin/sh

. $(dirname $0)/functions

git fetch

set_branch_name

echo "branch_name='$branch_name'"

if [ "$branch_name" == "" ] ; then
	echo "Not on a branch (for $branch_name)"
	exit 1
fi

describe=$(git describe --tags --always HEAD)
case "$describe" in
	r/*)
		describe=${describe##r\/}
		echo "$branch_name-$describe"
		;;
	*)
		echo "No commit number tag found"
		exit 1
		;;
esac

